version: '3.8'

services:
  campusconnect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campusconnect_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
